[build]
command = "npm run build"  # Replace with your build command
publish = "dist"  # Replace with the build output directory

[build.publish]
directory = "C:\Users\siddharth.s\Documents\MyCura.com\Mycura"
